cookie:
  expiry_days: 0
  key: "calvin-ai-signature-key"
  name: calvin-ai-cookie
credentials:
  usernames:
    sanjit:
      email: sanjit@gmail.com
      name: John Smith
      password: $2b$12$.QlbKvMrLpZVLvVxjYiKm./t3B7XsBvfDLqte2V8QTJHtOFIk6RMW
    sanjitjuneja:
      email: sanjit.j55@gmail.com
      name: Sanjit Juneja
      password: $2b$12$qr/H/1vRUb8M.0RUQIfNFu2P8aHpapRiJxZWmcqY5M9O143.ercX.
preauthorized:
  emails:
    -
